apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: monitoring-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
