apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: monitoring-dashboard
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: monitoring_dashboard
